name: CI

on:
  pull_request:
    branches: 
      — main

jobs:
  
  build:
    name: Build and Test
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ‘1.20.0’
      
      - name: Install Dependencies
        shell: bash
        run: |
          go mod download
          go mod tidy

      - name: Run Tests
        shell: bash
        run: |
          go test

      - name: Build
        run: go build ./...